<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/shivam/Projects/jerry-birthday/blender/models/birthday-set.glb --root https://cdn.theether.in/ --types --printwidth 120 --precision 2 --draco true
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'NurbsPath.090Action'
  type GLTFResult = {
    nodes: {
      back: THREE.Mesh
      ['bench-wood']: THREE.Mesh
      dividers: THREE.Mesh
      doors: THREE.Mesh
      drawer: THREE.Mesh
      frames: THREE.Mesh
      Handles: THREE.Mesh
      ['inner-side']: THREE.Mesh
      shelfs: THREE.Mesh
      side: THREE.Mesh
      WindowR: THREE.Mesh
      WindowR_1: THREE.Mesh
      ['slider-frame']: THREE.Mesh
      ['top-bottom']: THREE.Mesh
      Cube006_1: THREE.Mesh
      Cube006_2: THREE.Mesh
      Cube001: THREE.Mesh
      Cube002: THREE.Mesh
      Cube005: THREE.Mesh
      Cube006: THREE.Mesh
      Cylinder003_1: THREE.Mesh
      Cylinder003_2: THREE.Mesh
      Cylinder003_3: THREE.Mesh
      Cylinder003_4: THREE.Mesh
      Mesh018: THREE.Mesh
      Mesh018_1: THREE.Mesh
      Mesh017: THREE.Mesh
      Mesh017_1: THREE.Mesh
      BASE: THREE.Mesh
      Plane001_1: THREE.Mesh
      Plane001_2: THREE.Mesh
      Plane003: THREE.Mesh
      Plane003_1: THREE.Mesh
      ['LIGHT1-SUPPORT1']: THREE.Mesh
      ['LIGHT1-SUPPORT2']: THREE.Mesh
      ['LIGHT1-SUPPORT3']: THREE.Mesh
      ['LIGHT2-SUPPORT1']: THREE.Mesh
      ['LIGHT2-SUPPORT2']: THREE.Mesh
      ['LIGHT2-SUPPORT3']: THREE.Mesh
      Circle010: THREE.Mesh
      Circle010_1: THREE.Mesh
      Circle009: THREE.Mesh
      Circle009_1: THREE.Mesh
      Circle008_1: THREE.Mesh
      Circle008_2: THREE.Mesh
      Circle007_1: THREE.Mesh
      Circle007_2: THREE.Mesh
      Circle006_1: THREE.Mesh
      Circle006_2: THREE.Mesh
      Cube004: THREE.Mesh
      Cube009: THREE.Mesh
      Cube010: THREE.Mesh
      Cube011: THREE.Mesh
      Cube012: THREE.Mesh
      Cube013: THREE.Mesh
      Cube014: THREE.Mesh
      Cube016: THREE.Mesh
      Cylinder: THREE.Mesh
      Cylinder002: THREE.Mesh
      Plane004: THREE.Mesh
      Plane004_1: THREE.Mesh
      Plane004_2: THREE.Mesh
      Plane004_3: THREE.Mesh
      Plane008: THREE.Mesh
      Plane009: THREE.Mesh
      Cube090: THREE.Mesh
      Cube090_1: THREE.Mesh
      Cube003_1: THREE.Mesh
      Cube007_1: THREE.Mesh
      Cube008_1: THREE.Mesh
      Cube015: THREE.Mesh
      Cube017: THREE.Mesh
      Cube018: THREE.Mesh
      Cube019: THREE.Mesh
      Cube020: THREE.Mesh
      Handle002: THREE.Mesh
      Plane006: THREE.Mesh
      Plane007: THREE.Mesh
      Plane010: THREE.Mesh
      Plane010_1: THREE.Mesh
      Plane010_2: THREE.Mesh
      Plane010_3: THREE.Mesh
      Cube109: THREE.Mesh
      Cube109_1: THREE.Mesh
      Cube109_2: THREE.Mesh
      Cube109_3: THREE.Mesh
      Logo: THREE.Mesh
      ['Mesh_Grid_(enable_if_you_want)']: THREE.Mesh
      Top_Panel: THREE.Mesh
      Cylinder024: THREE.Mesh
      Cylinder024_1: THREE.Mesh
      Indication_lights: THREE.Mesh
      Play_Switch: THREE.Mesh
      Texts: THREE.Mesh
      Cylinder009: THREE.Mesh
      Cylinder009_1: THREE.Mesh
      Cylinder023: THREE.Mesh
      Cylinder023_1: THREE.Mesh
      Plane011: THREE.Mesh
      Plane011_1: THREE.Mesh
      Plane011_2: THREE.Mesh
      Plane011_3: THREE.Mesh
      StickyNote: THREE.Mesh
      StickyNote001: THREE.Mesh
      StickyNote002: THREE.Mesh
      StickyNote003: THREE.Mesh
      StickyNote004: THREE.Mesh
      StickyNote005: THREE.Mesh
      StickyNote006: THREE.Mesh
      StickyNote007: THREE.Mesh
      StickyNote008: THREE.Mesh
      StickyNote009: THREE.Mesh
      StickyNote010: THREE.Mesh
      StickyNote011: THREE.Mesh
      StickyNote012: THREE.Mesh
      StickyNote013: THREE.Mesh
      StickyNote014: THREE.Mesh
      StickyNote015: THREE.Mesh
      Circle005: THREE.Mesh
      Circle006: THREE.Mesh
      Circle007: THREE.Mesh
      Circle008: THREE.Mesh
      Plane001: THREE.Mesh
      NurbsPath090: THREE.Mesh
      Cube021: THREE.Mesh
      Cube022: THREE.Mesh
      Cube023: THREE.Mesh
      Cube024: THREE.Mesh
      Cylinder004_1: THREE.Mesh
      Cylinder004_2: THREE.Mesh
      Cylinder005_1: THREE.Mesh
      Cylinder005_2: THREE.Mesh
      Cylinder006: THREE.Mesh
      Cylinder006_1: THREE.Mesh
      Plane028: THREE.Mesh
      Plane028_1: THREE.Mesh
      Text: THREE.Mesh
      TableLight: THREE.Mesh
      TableLight_1: THREE.Mesh
      TableLight_2: THREE.Mesh
      Front_Wall: THREE.Mesh
      Side_Wall: THREE.Mesh
      Floor: THREE.Mesh
      Cube032: THREE.Mesh
      Cube032_1: THREE.Mesh
      Cube032_2: THREE.Mesh
      Cylinder_1: THREE.Mesh
      Cylinder_2: THREE.Mesh
      Cylinder_3: THREE.Mesh
      Mesh: THREE.Mesh
      Mesh_1: THREE.Mesh
    }
    materials: {
      ['CC0Textures/Wood003/2K-JPG']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
      Handle_material: THREE.MeshStandardMaterial
      Window_material: THREE.MeshStandardMaterial
      ['Laminate Sheet']: THREE.MeshStandardMaterial
      ['Metallic Gold']: THREE.MeshStandardMaterial
      ['Material.003']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['hard plastiv']: THREE.MeshStandardMaterial
      ['Hard Plastic Texturized']: THREE.MeshStandardMaterial
      ['Plaster white rough']: THREE.MeshStandardMaterial
      metal: THREE.MeshStandardMaterial
      wood: THREE.MeshStandardMaterial
      CREAMY: THREE.MeshStandardMaterial
      LED: THREE.MeshStandardMaterial
      Plastic: THREE.MeshStandardMaterial
      ShinyPlastic: THREE.MeshStandardMaterial
      LeatherCougar: THREE.MeshStandardMaterial
      Metallic: THREE.MeshStandardMaterial
      LeatherCougar2: THREE.MeshStandardMaterial
      Leather: THREE.MeshStandardMaterial
      Orange: THREE.MeshStandardMaterial
      ['Leather.001']: THREE.MeshStandardMaterial
      ['Leather.002']: THREE.MeshStandardMaterial
      Belt: THREE.MeshStandardMaterial
      ['Metallic.001']: THREE.MeshStandardMaterial
      ['Back Panel']: THREE.MeshStandardMaterial
      ['Back Panel Extras']: THREE.MeshStandardMaterial
      ['Metal-2']: THREE.MeshStandardMaterial
      Screws: THREE.MeshStandardMaterial
      ['Leather.003']: THREE.MeshStandardMaterial
      ['Mesh Panel']: THREE.MeshStandardMaterial
      ['Legs.001']: THREE.MeshStandardMaterial
      Logo: THREE.MeshStandardMaterial
      Mesh: THREE.MeshStandardMaterial
      ['Metal-1']: THREE.MeshStandardMaterial
      ['Metal-1']: THREE.MeshStandardMaterial
      Buttons_Black: THREE.MeshStandardMaterial
      ['Indication Lights']: THREE.MeshStandardMaterial
      Texts: THREE.MeshStandardMaterial
      WB_Metal: THREE.MeshStandardMaterial
      WB_Wood: THREE.MeshStandardMaterial
      WB_Plastic: THREE.MeshStandardMaterial
      WB_Board: THREE.MeshStandardMaterial
      ['Post-It Notes']: THREE.MeshStandardMaterial
      ['Car plastic dark']: THREE.MeshStandardMaterial
      ['aluminium used']: THREE.MeshStandardMaterial
      ['Material.009']: THREE.MeshStandardMaterial
      ['Metal Wire Mesh']: THREE.MeshStandardMaterial
      ['Metal preto']: THREE.MeshStandardMaterial
      ['Metal cromado']: THREE.MeshStandardMaterial
      ['Plastic Shader']: THREE.MeshStandardMaterial
      ['Metal preto.001']: THREE.MeshStandardMaterial
      ['paper.002']: THREE.MeshStandardMaterial
      ['paper.001']: THREE.MeshStandardMaterial
      ['white chocolate']: THREE.MeshStandardMaterial
      Marble_White: THREE.MeshPhysicalMaterial
      PaintedBronze: THREE.MeshStandardMaterial
      Legs: THREE.MeshStandardMaterial
      ['Parquet Flooring']: THREE.MeshStandardMaterial
      ['Lacquered Bamboo Parquet Wood Floor']: THREE.MeshStandardMaterial
      ['PORTA_TINTA.001']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      quadro2_figura: THREE.MeshStandardMaterial
      Wood: THREE.MeshPhysicalMaterial
      Aluminium: THREE.MeshPhysicalMaterial
      ['Black Rubber']: THREE.MeshStandardMaterial
      prop_laptop_lenovo_body: THREE.MeshStandardMaterial
      prop_laptop_lenovo_screen: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('https://cdn.theether.in/birthday-set.glb', {
    useDraco: true
  })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Wardrobe-1" position={[1.21, 0, 2.52]} rotation={[Math.PI, 0, Math.PI]}>
        <T.Mesh
          name="back"
          geometry={gltf.nodes.back.geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[0.31, 1.08, -0.28]}
        />
        <T.Mesh
          name="bench-wood"
          geometry={gltf.nodes['bench-wood'].geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[0.66, 0.45, -0.03]}
        />
        <T.Mesh
          name="dividers"
          geometry={gltf.nodes.dividers.geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[0.02, 2.08, -0.01]}
        />
        <T.Mesh
          name="doors"
          geometry={gltf.nodes.doors.geometry}
          material={gltf.materials['Material.007']}
          position={[0.01, 2.08, 0.27]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 0.62, 1.1]}
        />
        <T.Mesh
          name="drawer"
          geometry={gltf.nodes.drawer.geometry}
          material={gltf.materials['Material.007']}
          position={[0.76, 0.66, 0.21]}
        />
        <T.Mesh
          name="frames"
          geometry={gltf.nodes.frames.geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[0.57, 1.44, -0.16]}
        />
        <T.Mesh
          name="Handles"
          geometry={gltf.nodes.Handles.geometry}
          material={gltf.materials.Handle_material}
          position={[0.01, 1.94, 0.3]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <T.Mesh
          name="inner-side"
          geometry={gltf.nodes['inner-side'].geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[0.12, 0.9, -0.03]}
        />
        <T.Mesh
          name="shelfs"
          geometry={gltf.nodes.shelfs.geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[0.52, 1.49, -0.15]}
        />
        <T.Mesh
          name="side"
          geometry={gltf.nodes.side.geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[-0.88, 0.9, -0.03]}
        />
        <T.Group name="slider" position={[-0.38, 0.95, 0.19]}>
          <T.Mesh name="WindowR" geometry={gltf.nodes.WindowR.geometry} material={gltf.materials.Window_material} />
          <T.Mesh
            name="WindowR_1"
            geometry={gltf.nodes.WindowR_1.geometry}
            material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          />
        </T.Group>
        <T.Mesh
          name="slider-frame"
          geometry={gltf.nodes['slider-frame'].geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[-0.38, 0.95, 0.19]}
        />
        <T.Mesh
          name="top-bottom"
          geometry={gltf.nodes['top-bottom'].geometry}
          material={gltf.materials['CC0Textures/Wood003/2K-JPG']}
          position={[-0.12, 1.4, -0.01]}
        />
      </T.Group>
      <T.Group name="Minimalistic_tv_unit" position={[0.1, 0.4, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <T.Group name="Cube" position={[0, 0.24, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh
            name="Cube006_1"
            geometry={gltf.nodes.Cube006_1.geometry}
            material={gltf.materials['Laminate Sheet']}
          />
          <T.Mesh
            name="Cube006_2"
            geometry={gltf.nodes.Cube006_2.geometry}
            material={gltf.materials['Laminate Sheet']}
          />
        </T.Group>
        <T.Mesh
          name="Cube001"
          geometry={gltf.nodes.Cube001.geometry}
          material={gltf.materials['Laminate Sheet']}
          position={[-0.66, 0.24, -0.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Cube002"
          geometry={gltf.nodes.Cube002.geometry}
          material={gltf.materials['Laminate Sheet']}
          position={[0.66, 0.24, -0.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Cube005"
          geometry={gltf.nodes.Cube005.geometry}
          material={gltf.materials['Laminate Sheet']}
          position={[0, 0, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Cube006"
          geometry={gltf.nodes.Cube006.geometry}
          material={gltf.materials['Metallic Gold']}
          position={[0.08, 0.14, -0.14]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <T.Group name="Cylinder001" position={[-0.53, 0.1, -0.21]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh
            name="Cylinder003_1"
            geometry={gltf.nodes.Cylinder003_1.geometry}
            material={gltf.materials['Material.003']}
          />
          <T.Mesh
            name="Cylinder003_2"
            geometry={gltf.nodes.Cylinder003_2.geometry}
            material={gltf.materials['Material.001']}
          />
          <T.Mesh
            name="Cylinder003_3"
            geometry={gltf.nodes.Cylinder003_3.geometry}
            material={gltf.materials['hard plastiv']}
          />
          <T.Mesh
            name="Cylinder003_4"
            geometry={gltf.nodes.Cylinder003_4.geometry}
            material={gltf.materials['Hard Plastic Texturized']}
          />
        </T.Group>
        <T.Group name="ento_statuet_01" position={[0.68, 0.1, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh
            name="Mesh018"
            geometry={gltf.nodes.Mesh018.geometry}
            material={gltf.materials['Plaster white rough']}
          />
          <T.Mesh name="Mesh018_1" geometry={gltf.nodes.Mesh018_1.geometry} material={gltf.materials.metal} />
        </T.Group>
        <T.Group name="ento_statuet_02" position={[0.59, 0.14, -0.29]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh name="Mesh017" geometry={gltf.nodes.Mesh017.geometry} material={gltf.materials.wood} />
          <T.Mesh name="Mesh017_1" geometry={gltf.nodes.Mesh017_1.geometry} material={gltf.materials.metal} />
        </T.Group>
      </T.Group>
      <T.Group name="Modern_Ceiling_Light_03" position={[0.1, 2.69, 1.3]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <T.Mesh name="BASE" geometry={gltf.nodes.BASE.geometry} material={gltf.materials.CREAMY} />
        <T.Group name="LIGHT-1">
          <T.Mesh name="Plane001_1" geometry={gltf.nodes.Plane001_1.geometry} material={gltf.materials.LED} />
          <T.Mesh name="Plane001_2" geometry={gltf.nodes.Plane001_2.geometry} material={gltf.materials.CREAMY} />
        </T.Group>
        <T.Group name="LIGHT-2">
          <T.Mesh name="Plane003" geometry={gltf.nodes.Plane003.geometry} material={gltf.materials.LED} />
          <T.Mesh name="Plane003_1" geometry={gltf.nodes.Plane003_1.geometry} material={gltf.materials.CREAMY} />
        </T.Group>
        <T.Mesh
          name="LIGHT1-SUPPORT1"
          geometry={gltf.nodes['LIGHT1-SUPPORT1'].geometry}
          material={gltf.materials.CREAMY}
        />
        <T.Mesh
          name="LIGHT1-SUPPORT2"
          geometry={gltf.nodes['LIGHT1-SUPPORT2'].geometry}
          material={gltf.materials.CREAMY}
        />
        <T.Mesh
          name="LIGHT1-SUPPORT3"
          geometry={gltf.nodes['LIGHT1-SUPPORT3'].geometry}
          material={gltf.materials.CREAMY}
        />
        <T.Mesh
          name="LIGHT2-SUPPORT1"
          geometry={gltf.nodes['LIGHT2-SUPPORT1'].geometry}
          material={gltf.materials.CREAMY}
        />
        <T.Mesh
          name="LIGHT2-SUPPORT2"
          geometry={gltf.nodes['LIGHT2-SUPPORT2'].geometry}
          material={gltf.materials.CREAMY}
        />
        <T.Mesh
          name="LIGHT2-SUPPORT3"
          geometry={gltf.nodes['LIGHT2-SUPPORT3'].geometry}
          material={gltf.materials.CREAMY}
        />
      </T.Group>
      <T.Group name="Gaming_Chair" position={[4.38, 0, 1.93]} rotation={[0, 0.86, 0]} scale={0.28}>
        <T.Group name="Circle" position={[-1.05, 2.47, 0.28]} rotation={[0, -1.17, Math.PI / 2]} scale={0.12}>
          <T.Mesh name="Circle010" geometry={gltf.nodes.Circle010.geometry} material={gltf.materials.Plastic} />
          <T.Mesh
            name="Circle010_1"
            geometry={gltf.nodes.Circle010_1.geometry}
            material={gltf.materials.ShinyPlastic}
          />
        </T.Group>
        <T.Group
          name="Circle001"
          position={[-0.78, 2.47, -0.96]}
          rotation={[-Math.PI, -0.75, -Math.PI / 2]}
          scale={0.12}
        >
          <T.Mesh name="Circle009" geometry={gltf.nodes.Circle009.geometry} material={gltf.materials.Plastic} />
          <T.Mesh
            name="Circle009_1"
            geometry={gltf.nodes.Circle009_1.geometry}
            material={gltf.materials.ShinyPlastic}
          />
        </T.Group>
        <T.Group name="Circle002" position={[0.49, 2.47, -1.15]} rotation={[Math.PI, 0.45, -Math.PI / 2]} scale={0.12}>
          <T.Mesh name="Circle008_1" geometry={gltf.nodes.Circle008_1.geometry} material={gltf.materials.Plastic} />
          <T.Mesh
            name="Circle008_2"
            geometry={gltf.nodes.Circle008_2.geometry}
            material={gltf.materials.ShinyPlastic}
          />
        </T.Group>
        <T.Group name="Circle003" position={[1.06, 2.47, 0.04]} rotation={[Math.PI, 1.12, -Math.PI / 2]} scale={0.12}>
          <T.Mesh name="Circle007_1" geometry={gltf.nodes.Circle007_1.geometry} material={gltf.materials.Plastic} />
          <T.Mesh
            name="Circle007_2"
            geometry={gltf.nodes.Circle007_2.geometry}
            material={gltf.materials.ShinyPlastic}
          />
        </T.Group>
        <T.Group name="Circle004" position={[0.08, 2.47, 0.9]} rotation={[0, 1, Math.PI / 2]} scale={0.12}>
          <T.Mesh name="Circle006_1" geometry={gltf.nodes.Circle006_1.geometry} material={gltf.materials.Plastic} />
          <T.Mesh
            name="Circle006_2"
            geometry={gltf.nodes.Circle006_2.geometry}
            material={gltf.materials.ShinyPlastic}
          />
        </T.Group>
        <T.Mesh
          name="Cube004"
          geometry={gltf.nodes.Cube004.geometry}
          material={gltf.materials.Plastic}
          position={[0.91, 3.71, -0.65]}
          rotation={[-0.04, -0.82, -0.03]}
        />
        <T.Mesh
          name="Cube009"
          geometry={gltf.nodes.Cube009.geometry}
          material={gltf.materials.Plastic}
          position={[-0.17, 2.21, -0.07]}
          rotation={[0, -0.82, 0]}
        />
        <T.Mesh
          name="Cube010"
          geometry={gltf.nodes.Cube010.geometry}
          material={gltf.materials.LeatherCougar}
          position={[0.21, 2.09, -0.43]}
          rotation={[-0.29, -0.8, -0.21]}
        />
        <T.Mesh
          name="Cube011"
          geometry={gltf.nodes.Cube011.geometry}
          material={gltf.materials.Plastic}
          position={[-0.17, 1.22, -0.07]}
          rotation={[0, -0.82, 0]}
        />
        <T.Mesh
          name="Cube012"
          geometry={gltf.nodes.Cube012.geometry}
          material={gltf.materials.Metallic}
          position={[-0.17, 0.55, -0.07]}
          rotation={[0, -0.82, 0]}
          scale={0.57}
        />
        <T.Mesh
          name="Cube013"
          geometry={gltf.nodes.Cube013.geometry}
          material={gltf.materials.Plastic}
          position={[-0.17, 2.21, -0.07]}
          rotation={[0, -0.82, 0]}
          scale={0.17}
        />
        <T.Mesh
          name="Cube014"
          geometry={gltf.nodes.Cube014.geometry}
          material={gltf.materials.Plastic}
          position={[0.6, 1.5, 0.54]}
          rotation={[0, -0.55, 0]}
          scale={0.04}
        />
        <T.Mesh
          name="Cube016"
          geometry={gltf.nodes.Cube016.geometry}
          material={gltf.materials.LeatherCougar2}
          position={[0.51, 3.86, -0.73]}
          rotation={[0.06, -0.82, 0.04]}
          scale={0.31}
        />
        <T.Mesh
          name="Cylinder"
          geometry={gltf.nodes.Cylinder.geometry}
          material={gltf.materials.Plastic}
          position={[-0.05, 0.74, -0.18]}
          rotation={[0, -0.82, 0]}
        />
        <T.Mesh
          name="Cylinder002"
          geometry={gltf.nodes.Cylinder002.geometry}
          material={gltf.materials.Plastic}
          position={[-0.32, 1.1, 0.07]}
          rotation={[-0.47, -0.76, -0.34]}
        />
        <T.Group name="Plane002" position={[-0.17, 2.21, -0.07]} rotation={[Math.PI / 2, 0, 0.82]}>
          <T.Mesh name="Plane004" geometry={gltf.nodes.Plane004.geometry} material={gltf.materials.Leather} />
          <T.Mesh name="Plane004_1" geometry={gltf.nodes.Plane004_1.geometry} material={gltf.materials.Orange} />
          <T.Mesh
            name="Plane004_2"
            geometry={gltf.nodes.Plane004_2.geometry}
            material={gltf.materials['Leather.001']}
          />
          <T.Mesh
            name="Plane004_3"
            geometry={gltf.nodes.Plane004_3.geometry}
            material={gltf.materials['Leather.002']}
          />
        </T.Group>
        <T.Mesh
          name="Plane008"
          geometry={gltf.nodes.Plane008.geometry}
          material={gltf.materials.Belt}
          position={[-0.17, 2.21, -0.07]}
          rotation={[Math.PI / 2, 0, 0.82]}
        />
        <T.Mesh
          name="Plane009"
          geometry={gltf.nodes.Plane009.geometry}
          material={gltf.materials.Belt}
          position={[0.3, 2.21, 0.43]}
          rotation={[Math.PI / 2, 0, 0.82]}
        />
        <T.Group name="Sit" position={[-0.17, 2.21, -0.07]} rotation={[0, -0.82, 0]}>
          <T.Mesh name="Cube090" geometry={gltf.nodes.Cube090.geometry} material={gltf.materials.Leather} />
          <T.Mesh name="Cube090_1" geometry={gltf.nodes.Cube090_1.geometry} material={gltf.materials.Orange} />
<!--          <T.Mesh-->
<!--            name="Cube003_1"-->
<!--            geometry={gltf.nodes.Cube003_1.geometry}-->
<!--            material={gltf.materials.Plastic}-->
<!--            position={[0.02, 0.58, 0.43]}-->
<!--          />-->
<!--          <T.Mesh-->
<!--            name="Cube007_1"-->
<!--            geometry={gltf.nodes.Cube007_1.geometry}-->
<!--            material={gltf.materials.Plastic}-->
<!--            position={[0, 0.04, 0.43]}-->
<!--            scale={0.06}-->
<!--          />-->
<!--          <T.Mesh-->
<!--            name="Cube008_1"-->
<!--            geometry={gltf.nodes.Cube008_1.geometry}-->
<!--            material={gltf.materials.Plastic}-->
<!--            position={[0, 0.05, 0]}-->
<!--          />-->
          <T.Mesh
            name="Cube015"
            geometry={gltf.nodes.Cube015.geometry}
            material={gltf.materials['Metallic.001']}
            position={[0, 1.6, -1.29]}
            rotation={[0, 0.02, 0]}
            scale={0.01}
          />
          <T.Mesh
            name="Cube017"
            geometry={gltf.nodes.Cube017.geometry}
            material={gltf.materials.Plastic}
            position={[0.36, 1.27, -1.25]}
            rotation={[-0.2, 0.03, -0.02]}
          />
          <T.Mesh
            name="Cube018"
            geometry={gltf.nodes.Cube018.geometry}
            material={gltf.materials.Plastic}
            position={[0.36, 1.27, -1.25]}
            rotation={[-0.2, 0.03, -0.02]}
            scale={0.98}
          />
          <T.Mesh
            name="Cube019"
            geometry={gltf.nodes.Cube019.geometry}
            material={gltf.materials.Plastic}
            position={[-0.33, 1.27, -1.25]}
            rotation={[-0.2, 0.03, -0.02]}
          />
          <T.Mesh
            name="Cube020"
            geometry={gltf.nodes.Cube020.geometry}
            material={gltf.materials.Plastic}
            position={[-0.33, 1.27, -1.25]}
            rotation={[-0.2, 0.03, -0.02]}
            scale={0.98}
          />
          <T.Mesh
            name="Handle002"
            geometry={gltf.nodes.Handle002.geometry}
            material={gltf.materials.Plastic}
            position={[0, 0.21, 0]}
          />
          <T.Mesh
            name="Plane006"
            geometry={gltf.nodes.Plane006.geometry}
            material={gltf.materials.Belt}
            position={[0.3, 1.53, 0.03]}
            rotation={[Math.PI / 2, 0, 0.05]}
          />
          <T.Mesh
            name="Plane007"
            geometry={gltf.nodes.Plane007.geometry}
            material={gltf.materials.Belt}
            position={[0.01, 1.65, -1.18]}
            rotation={[Math.PI / 2, 0, 0.05]}
            scale={0.03}
          />
        </T.Group>
      </T.Group>
      <T.Group name="Marshall_Speaker" position={[0.89, 1.31, 2.67]} rotation={[Math.PI, 0, Math.PI]}>
        <T.Group name="Back_panel" position={[0, 0.1, -0.08]}>
          <T.Mesh name="Plane010" geometry={gltf.nodes.Plane010.geometry} material={gltf.materials['Back Panel']} />
          <T.Mesh
            name="Plane010_1"
            geometry={gltf.nodes.Plane010_1.geometry}
            material={gltf.materials['Back Panel Extras']}
          />
          <T.Mesh name="Plane010_2" geometry={gltf.nodes.Plane010_2.geometry} material={gltf.materials['Metal-2']} />
          <T.Mesh name="Plane010_3" geometry={gltf.nodes.Plane010_3.geometry} material={gltf.materials.Screws} />
        </T.Group>
        <T.Group name="Box" position={[0, 0.1, 0]}>
          <T.Mesh name="Cube109" geometry={gltf.nodes.Cube109.geometry} material={gltf.materials['Leather.003']} />
          <T.Mesh name="Cube109_1" geometry={gltf.nodes.Cube109_1.geometry} material={gltf.materials['Metal-2']} />
          <T.Mesh name="Cube109_2" geometry={gltf.nodes.Cube109_2.geometry} material={gltf.materials['Mesh Panel']} />
          <T.Mesh name="Cube109_3" geometry={gltf.nodes.Cube109_3.geometry} material={gltf.materials['Legs.001']} />
        </T.Group>
        <T.Mesh
          name="Logo"
          geometry={gltf.nodes.Logo.geometry}
          material={gltf.materials.Logo}
          position={[0, 0.11, 0.1]}
        />
        <T.Mesh
          name="Mesh_Grid_(enable_if_you_want)"
          geometry={gltf.nodes['Mesh_Grid_(enable_if_you_want)'].geometry}
          material={gltf.materials.Mesh}
          position={[0, 0.1, 0.1]}
        />
        <T.Mesh
          name="Top_Panel"
          geometry={gltf.nodes.Top_Panel.geometry}
          material={gltf.materials['Metal-1']}
          position={[0, 0.18, 0]}
        >
          <T.Group name="Power_Switch" />
          <T.Group name="Bass_Knob">
            <T.Mesh
              name="Cylinder024"
              geometry={gltf.nodes.Cylinder024.geometry}
              material={gltf.materials['Metal-1']}
            />
            <T.Mesh
              name="Cylinder024_1"
              geometry={gltf.nodes.Cylinder024_1.geometry}
              material={gltf.materials.Buttons_Black}
            />
          </T.Group>
          <T.Mesh
            name="Indication_lights"
            geometry={gltf.nodes.Indication_lights.geometry}
            material={gltf.materials['Indication Lights']}
          />
          <T.Mesh name="Play_Switch" geometry={gltf.nodes.Play_Switch.geometry} material={gltf.materials['Metal-1']} />
          <T.Mesh name="Texts" geometry={gltf.nodes.Texts.geometry} material={gltf.materials.Texts} />
          <T.Group name="Treble_Knob">
            <T.Mesh
              name="Cylinder009"
              geometry={gltf.nodes.Cylinder009.geometry}
              material={gltf.materials['Metal-1']}
            />
            <T.Mesh
              name="Cylinder009_1"
              geometry={gltf.nodes.Cylinder009_1.geometry}
              material={gltf.materials.Buttons_Black}
            />
          </T.Group>
          <T.Group name="Volume_Knob">
            <T.Mesh
              name="Cylinder023"
              geometry={gltf.nodes.Cylinder023.geometry}
              material={gltf.materials['Metal-1']}
            />
            <T.Mesh
              name="Cylinder023_1"
              geometry={gltf.nodes.Cylinder023_1.geometry}
              material={gltf.materials.Buttons_Black}
            />
          </T.Group>
        </T.Mesh>
      </T.Group>
      <T.Group name="Whiteboard" position={[4.38, 1.89, 2.77]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.69}>
        <T.Group name="Whiteboard001" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.46}>
          <T.Mesh name="Plane011" geometry={gltf.nodes.Plane011.geometry} material={gltf.materials.WB_Metal} />
          <T.Mesh name="Plane011_1" geometry={gltf.nodes.Plane011_1.geometry} material={gltf.materials.WB_Wood} />
          <T.Mesh name="Plane011_2" geometry={gltf.nodes.Plane011_2.geometry} material={gltf.materials.WB_Plastic} />
          <T.Mesh name="Plane011_3" geometry={gltf.nodes.Plane011_3.geometry} material={gltf.materials.WB_Board} />
        </T.Group>
      </T.Group>
      <T.Group name="Sticky_Notes" position={[3.99, 1.51, 2.76]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <T.Mesh
          name="StickyNote"
          geometry={gltf.nodes.StickyNote.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.13, 0, 0.1]}
          rotation={[0, -0.1, 0]}
        />
        <T.Mesh
          name="StickyNote001"
          geometry={gltf.nodes.StickyNote001.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.04, 0, 0.1]}
          rotation={[0, 0.09, 0]}
        />
        <T.Mesh
          name="StickyNote002"
          geometry={gltf.nodes.StickyNote002.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.05, 0, 0.1]}
          rotation={[0, -0.03, 0]}
        />
        <T.Mesh
          name="StickyNote003"
          geometry={gltf.nodes.StickyNote003.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.13, 0, 0.1]}
          rotation={[0, 0.07, 0]}
        />
        <T.Mesh
          name="StickyNote004"
          geometry={gltf.nodes.StickyNote004.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.13, 0, 0.01]}
        />
        <T.Mesh
          name="StickyNote005"
          geometry={gltf.nodes.StickyNote005.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.04, 0, 0.01]}
          rotation={[0, 0.01, 0]}
        />
        <T.Mesh
          name="StickyNote006"
          geometry={gltf.nodes.StickyNote006.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.05, 0, 0.01]}
          rotation={[0, 0.03, 0]}
        />
        <T.Mesh
          name="StickyNote007"
          geometry={gltf.nodes.StickyNote007.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.13, 0, 0.01]}
          rotation={[0, 0.03, 0]}
        />
        <T.Mesh
          name="StickyNote008"
          geometry={gltf.nodes.StickyNote008.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.13, 0, -0.08]}
          rotation={[0, -0.06, 0]}
        />
        <T.Mesh
          name="StickyNote009"
          geometry={gltf.nodes.StickyNote009.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.04, 0, -0.08]}
          rotation={[0, 0.08, 0]}
        />
        <T.Mesh
          name="StickyNote010"
          geometry={gltf.nodes.StickyNote010.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.05, 0, -0.08]}
          rotation={[0, -0.05, 0]}
        />
        <T.Mesh
          name="StickyNote011"
          geometry={gltf.nodes.StickyNote011.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.13, 0, -0.08]}
          rotation={[0, 0.06, 0]}
        />
        <T.Mesh
          name="StickyNote012"
          geometry={gltf.nodes.StickyNote012.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.13, 0, -0.17]}
          rotation={[0, -0.01, 0]}
        />
        <T.Mesh
          name="StickyNote013"
          geometry={gltf.nodes.StickyNote013.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[-0.04, 0, -0.17]}
          rotation={[0, -0.06, 0]}
        />
        <T.Mesh
          name="StickyNote014"
          geometry={gltf.nodes.StickyNote014.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.05, 0, -0.17]}
          rotation={[0, -0.01, 0]}
        />
        <T.Mesh
          name="StickyNote015"
          geometry={gltf.nodes.StickyNote015.geometry}
          material={gltf.materials['Post-It Notes']}
          position={[0.13, 0, -0.17]}
          rotation={[0, 0.05, 0]}
        />
      </T.Group>
      <T.Group name="Coffee_Cup" position={[2.53, 0.75, -2.15]}>
        <T.Mesh
          name="Circle005"
          geometry={gltf.nodes.Circle005.geometry}
          material={gltf.materials['Car plastic dark']}
          position={[0, 0.11, 0]}
        />
        <T.Mesh
          name="Circle006"
          geometry={gltf.nodes.Circle006.geometry}
          material={gltf.materials['Car plastic dark']}
          position={[0, 0.1, 0]}
        />
        <T.Mesh
          name="Circle007"
          geometry={gltf.nodes.Circle007.geometry}
          material={gltf.materials['aluminium used']}
          position={[0, 0.01, 0]}
        />
        <T.Mesh
          name="Circle008"
          geometry={gltf.nodes.Circle008.geometry}
          material={gltf.materials['Car plastic dark']}
        />
        <T.Mesh
          name="Plane001"
          geometry={gltf.nodes.Plane001.geometry}
          material={gltf.materials['Car plastic dark']}
          position={[0, 0.11, 0.02]}
        />
      </T.Group>
      <T.Group name="Pen_holder_with_supplies" position={[3.92, 0.81, 2.65]} rotation={[Math.PI, 0, Math.PI]}>
        <T.Mesh
          name="NurbsPath090"
          geometry={gltf.nodes.NurbsPath090.geometry}
          material={gltf.materials['Material.009']}
          position={[-0.08, 0.02, 0.01]}
          rotation={[-0.35, 0, 0.1]}
        />
        <T.Mesh
          name="Cube021"
          geometry={gltf.nodes.Cube021.geometry}
          material={gltf.materials['Metal Wire Mesh']}
          position={[0, 0.05, 0]}
        />
        <T.Mesh
          name="Cube022"
          geometry={gltf.nodes.Cube022.geometry}
          material={gltf.materials['Metal Wire Mesh']}
          position={[0, 0.05, 0]}
        />
        <T.Mesh
          name="Cube023"
          geometry={gltf.nodes.Cube023.geometry}
          material={gltf.materials['Metal Wire Mesh']}
          position={[0, 0.05, 0]}
        />
        <T.Mesh
          name="Cube024"
          geometry={gltf.nodes.Cube024.geometry}
          material={gltf.materials['Metal preto']}
          position={[0, 0.05, 0]}
        />
        <T.Group name="Cylinder003" position={[-0.09, 0.06, -0.04]}>
          <T.Mesh
            name="Cylinder004_1"
            geometry={gltf.nodes.Cylinder004_1.geometry}
            material={gltf.materials['Metal cromado']}
          />
          <T.Mesh
            name="Cylinder004_2"
            geometry={gltf.nodes.Cylinder004_2.geometry}
            material={gltf.materials['Plastic Shader']}
          />
        </T.Group>
        <T.Group name="Cylinder004" position={[-0.04, 0, -0.03]}>
          <T.Mesh
            name="Cylinder005_1"
            geometry={gltf.nodes.Cylinder005_1.geometry}
            material={gltf.materials['Metal preto.001']}
          />
          <T.Mesh
            name="Cylinder005_2"
            geometry={gltf.nodes.Cylinder005_2.geometry}
            material={gltf.materials['Metal cromado']}
          />
        </T.Group>
        <T.Group name="Cylinder005" position={[-0.04, 0, -0.03]}>
          <T.Mesh
            name="Cylinder006"
            geometry={gltf.nodes.Cylinder006.geometry}
            material={gltf.materials['Metal preto']}
          />
          <T.Mesh
            name="Cylinder006_1"
            geometry={gltf.nodes.Cylinder006_1.geometry}
            material={gltf.materials['Metal cromado']}
          />
        </T.Group>
        <T.Group name="Plane" position={[0.05, 0, 0]}>
          <T.Mesh name="Plane028" geometry={gltf.nodes.Plane028.geometry} material={gltf.materials['paper.002']} />
          <T.Mesh name="Plane028_1" geometry={gltf.nodes.Plane028_1.geometry} material={gltf.materials['paper.001']} />
        </T.Group>
      </T.Group>
      <T.Mesh
        name="Text"
        geometry={gltf.nodes.Text.geometry}
        material={gltf.materials['white chocolate']}
        position={[0.13, 3, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <T.Group name="Moder_Dining_Table_White" position={[3.5, 0, -2.5]} rotation={[0, Math.PI / 2, 0]}>
        <T.Mesh name="TableLight" geometry={gltf.nodes.TableLight.geometry} material={gltf.materials.Marble_White} />
        <T.Mesh
          name="TableLight_1"
          geometry={gltf.nodes.TableLight_1.geometry}
          material={gltf.materials.PaintedBronze}
        />
        <T.Mesh name="TableLight_2" geometry={gltf.nodes.TableLight_2.geometry} material={gltf.materials.Legs} />
      </T.Group>
      <T.Mesh
        name="Front_Wall"
        geometry={gltf.nodes.Front_Wall.geometry}
        material={gltf.materials['Parquet Flooring']}
        position={[0, 2, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.1, 2, 3]}
      />
      <T.Mesh
        name="Side_Wall"
        geometry={gltf.nodes.Side_Wall.geometry}
        material={gltf.materials['Parquet Flooring']}
        position={[2.9, 2, 2.9]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 2, 3]}
      />
      <T.Mesh
        name="Floor"
        geometry={gltf.nodes.Floor.geometry}
        material={gltf.materials['Lacquered Bamboo Parquet Wood Floor']}
        position={[2.9, 0, -0.01]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.1, 3, 3]}
      />
      <T.Group name="Painting_with_frame" position={[1.89, 3, 2.77]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <T.Mesh name="Cube032" geometry={gltf.nodes.Cube032.geometry} material={gltf.materials['PORTA_TINTA.001']} />
        <T.Mesh name="Cube032_1" geometry={gltf.nodes.Cube032_1.geometry} material={gltf.materials['Material.002']} />
        <T.Mesh name="Cube032_2" geometry={gltf.nodes.Cube032_2.geometry} material={gltf.materials.quadro2_figura} />
      </T.Group>
      <T.Group name="Study_Table" position={[4.33, 0, 2.46]}>
        <T.Mesh name="Cylinder_1" geometry={gltf.nodes.Cylinder_1.geometry} material={gltf.materials.Wood} />
        <T.Mesh name="Cylinder_2" geometry={gltf.nodes.Cylinder_2.geometry} material={gltf.materials.Aluminium} />
        <T.Mesh name="Cylinder_3" geometry={gltf.nodes.Cylinder_3.geometry} material={gltf.materials['Black Rubber']} />
      </T.Group>
      <T.Group name="Lenovo_laptop" position={[4.4, 0.82, 2.61]} rotation={[Math.PI, 0, Math.PI]} scale={0}>
        <T.Mesh name="Mesh" geometry={gltf.nodes.Mesh.geometry} material={gltf.materials.prop_laptop_lenovo_body} />
        <T.Mesh
          name="Mesh_1"
          geometry={gltf.nodes.Mesh_1.geometry}
          material={gltf.materials.prop_laptop_lenovo_screen}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
