<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/shivam/Projects/jerry-birthday/static/models/jerry.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  const { actions } = useGltfAnimations()

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  let currentActionKey = 'idle'
  $: $actions[currentActionKey]?.play()


  type GLTFResult = {
    nodes: {
      Wolf3D_Hair: THREE.SkinnedMesh
      Wolf3D_Glasses: THREE.SkinnedMesh
      Wolf3D_Body: THREE.SkinnedMesh
      Wolf3D_Outfit_Bottom: THREE.SkinnedMesh
      Wolf3D_Outfit_Footwear: THREE.SkinnedMesh
      Wolf3D_Outfit_Top: THREE.SkinnedMesh
      EyeLeft: THREE.SkinnedMesh
      EyeRight: THREE.SkinnedMesh
      Wolf3D_Head: THREE.SkinnedMesh
      Wolf3D_Teeth: THREE.SkinnedMesh
      Hips: THREE.Bone
    }
    materials: {
      Wolf3D_Hair: THREE.MeshStandardMaterial
      Wolf3D_Glasses: THREE.MeshStandardMaterial
      Wolf3D_Body: THREE.MeshStandardMaterial
      Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial
      Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial
      Wolf3D_Outfit_Top: THREE.MeshStandardMaterial
      Wolf3D_Eye: THREE.MeshStandardMaterial
      Wolf3D_Skin: THREE.MeshStandardMaterial
      Wolf3D_Teeth: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/jerry.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T is={gltf.nodes.Hips} />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Hair.geometry}
      material={gltf.materials.Wolf3D_Hair}
      skeleton={gltf.nodes.Wolf3D_Hair.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Glasses.geometry}
      material={gltf.materials.Wolf3D_Glasses}
      skeleton={gltf.nodes.Wolf3D_Glasses.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Body.geometry}
      material={gltf.materials.Wolf3D_Body}
      skeleton={gltf.nodes.Wolf3D_Body.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Outfit_Bottom.geometry}
      material={gltf.materials.Wolf3D_Outfit_Bottom}
      skeleton={gltf.nodes.Wolf3D_Outfit_Bottom.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Outfit_Footwear.geometry}
      material={gltf.materials.Wolf3D_Outfit_Footwear}
      skeleton={gltf.nodes.Wolf3D_Outfit_Footwear.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Outfit_Top.geometry}
      material={gltf.materials.Wolf3D_Outfit_Top}
      skeleton={gltf.nodes.Wolf3D_Outfit_Top.skeleton}
    />
    <T.SkinnedMesh
      name="EyeLeft"
      geometry={gltf.nodes.EyeLeft.geometry}
      material={gltf.materials.Wolf3D_Eye}
      skeleton={gltf.nodes.EyeLeft.skeleton}
      morphTargetDictionary={gltf.nodes.EyeLeft.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.EyeLeft.morphTargetInfluences}
    />
    <T.SkinnedMesh
      name="EyeRight"
      geometry={gltf.nodes.EyeRight.geometry}
      material={gltf.materials.Wolf3D_Eye}
      skeleton={gltf.nodes.EyeRight.skeleton}
      morphTargetDictionary={gltf.nodes.EyeRight.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.EyeRight.morphTargetInfluences}
    />
    <T.SkinnedMesh
      name="Wolf3D_Head"
      geometry={gltf.nodes.Wolf3D_Head.geometry}
      material={gltf.materials.Wolf3D_Skin}
      skeleton={gltf.nodes.Wolf3D_Head.skeleton}
      morphTargetDictionary={gltf.nodes.Wolf3D_Head.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.Wolf3D_Head.morphTargetInfluences}
    />
    <T.SkinnedMesh
      name="Wolf3D_Teeth"
      geometry={gltf.nodes.Wolf3D_Teeth.geometry}
      material={gltf.materials.Wolf3D_Teeth}
      skeleton={gltf.nodes.Wolf3D_Teeth.skeleton}
      morphTargetDictionary={gltf.nodes.Wolf3D_Teeth.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.Wolf3D_Teeth.morphTargetInfluences}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
